sonar.projectKey=attendance-regulizer
sonar.projectName=Attendance Regulizer
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.exclusions=node_modules/**,dist/**,scripts/**,deploy.ps1,**/*.spec.ts,**/*.test.ts,.vscode/**